organization: tegioz-tests
teams:
  - name: team1
    maintainers:
      - tegioz
    members:
      - cynthia-sg
  - name: team2
    maintainers:
      - tegioz
    members: []
  - name: team3
    maintainers:
      - cynthia-sg
    members:
      - Clomonitor5
  - name: team4
    maintainers:
      - tegioz
    members: []
  - name: team5
    maintainers:
      - cynthia-sg
      - tegioz
    members:
      - CloMonitor3
      - Clomonitor4
      - Clomonitor5
repositories:
  - name: .github
    external_collaborators: {}
    visibility: private
  - name: .clowarden
    external_collaborators:
      cynthia-sg: admin
    visibility: public
  - name: gitvote-tests
    teams:
      team2: read
    external_collaborators:
      Clomonitor1: write
      Clomonitor2: write
      Clomonitor3: write
      Clomonitor4: write
      Clomonitor5: write
      Clomonitor6: read
    visibility: private
  - name: sample-repo
    teams:
      team3: admin
    external_collaborators:
      Clomonitor3: read
      Clomonitor4: admin
    visibility: private
