organization: tegioz-tests
teams:
  - name: team1
    maintainers:
      - tegioz
    members:
      - cynthia-sg
  - name: team2
    maintainers:
      - tegioz
    members: []
  - name: team3
    maintainers:
      - cynthia-sg
    members: []
  - name: team4
    maintainers:
      - cynthia-sg
      - cynthia-sg
    members: []
  - name: team5
    maintainers:
      - tegioz
    members:
      - cynthia-sg
      - cynthia-sg
  - name: team6
    maintainers:
      - tegioz
  - name: group1
    maintainers:
      - cynthia-sg
    members:
      - tegioz
    formation:
      - team4
      - team6
repositories:
  - name: .github
    external_collaborators: {}
    visibility: private
  - name: .clowarden
    external_collaborators:
      cynthia-sg: admin
    visibility: private
  - name: gitvote-tests
    teams:
      team2: read
    external_collaborators: {}
    visibility: private
  - name: sample-repo
    teams:
      team1: write
      team2: read
    external_collaborators: {}
    visibility: private
  - name: new-repo
    teams:
      team4: write
    external_collaborators:
      Clomonitor1: read
      Clomonitor1: admin
    visibility: private
