organization: tegioz-tests
teams:
  - name: team1
    maintainers:
      - tegioz
      - artifacthubio
    members:
      - cynthia-sg
  - name: team2
    maintainers:
      - tegioz
    members: []
  - name: team3
    maintainers:
      - cynthia-sg
    members: []
repositories:
  - name: .github
    external_collaborators: {}
    visibility: private
  - name: .clowarden
    external_collaborators:
      cynthia-sg: admin
    visibility: private
  - name: gitvote-tests
    teams:
      team2: read
    external_collaborators: {}
    visibility: private
  - name: sample-repo
    teams:
      team1: write
      team3: read
    external_collaborators: {}
    visibility: private
