organization: tegioz-tests
teams:
  - name: team1
    maintainers:
      - tegioz
    members:
      - cynthia-sg
  - name: team2
    maintainers:
      - tegioz
    members: []
  - name: team3
    maintainers:
      - cynthia-sg
    members: []
  - name: team4
    maintainers:
      - cynthia-sg
  - name: team5
    maintainers:
      - cynthia-sg
      - Clomonitor1    
    members:
      - Clomonitor2
  - name: team6
    formation:
      - team5
      - team6
repositories:
  - name: .github
    external_collaborators: {}
    visibility: private
  - name: .clowarden
    external_collaborators:
      cynthia-sg: admin
    visibility: private
  - name: gitvote-tests
    teams:
      team2: read
    external_collaborators: {}
    visibility: private
  - name: sample-repo
    teams:
      team1: write
      team2: read
    external_collaborators: {}
    visibility: private
  - name: test
    teams:
      team6: admin
    external_collaborators:
      Clomonitor3: read
    visibility: private
  - name: test-2
    teams:
      team6: admin
    external_collaborators:
      Clomonitor3: read
      Clomonitor1: write
    visibility: private
    
