organization: tegioz-tests
teams:
  - name: team1
    maintainers:
      - tegioz
      - cynthia-sg
    members: []
  - name: team2
    maintainers:
      - tegioz
    members: []
  - name: team3
    maintainers:
      - cynthia-sg
    members: []
  - name: team4
    maintainers:
      - cynthia-sg
    members:
      - Clomonitor1
      - Clomonitor2
      - Clomonitor3
  - name: team8
    maintainers:
      - Clomonitor1
    members:
      - Clomonitor2
repositories:
  - name: .github
    external_collaborators: {}
    visibility: private
  - name: .clowarden
    external_collaborators:
      cynthia-sg: admin
    visibility: private
  - name: gitvote-tests
    teams:
      team2: read
    external_collaborators: {}
    visibility: private
  - name: sample-repo
    teams:
      team1: write
      team3: read
    external_collaborators: {}
    visibility: private
  - name: sample-repo-cin
    external_collaborators:
      Clomonitor1: write
    visibility: private
  - name: repo1
    teams:
      team8: write
    external_collaborators:
      Clomonitor1: read
      artifacthubio: read
    visibility: public
